// Aba de agendamentos: lê/grava a aba Agendamentos pelo backend existente.
var rowsAg=[]; var busyAg=false; var profCacheAg=null;
function normAg(v){return String(v==null?'':v).trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ');}
// Mapa pessoa -> profissionais (histórico completo), vindo de Pessoas atendidas
// (coluna "Profissional"). Também junta a lista de profissionais para o datalist.
function profMapAg(){if(profCacheAg)return profCacheAg;var list=window.__emultiPessoasAtendidas&&window.__emultiPessoasAtendidas();if(!list||!Array.isArray(list.rows)||!list.rows.length)return null;var map={},nomes={};list.rows.forEach(function(r){var txt=String(r[5]==null?'':r[5]);if(!txt||txt==='—')return;map[normAg(r[0])]=normAg(txt);txt.split(',').forEach(function(n){n=n.trim();if(n&&n!=='—')nomes[n]=1;});});profCacheAg={map:map,nomes:Object.keys(nomes).sort(function(a,b){return a.localeCompare(b,'pt-BR');})};return profCacheAg;}
function fillProfAg(){var dl=document.getElementById('agendamentosProfissionais'),c=profMapAg();if(!dl||!c)return;dl.innerHTML=c.nomes.map(function(n){return '<option value="'+escAg(n)+'"></option>';}).join('');}
function apiAg(payload){var api=window.PAINEL_API,token=window.painelToken&&window.painelToken();if(!api||!token)return Promise.reject(Error('Sessão não iniciada. Entre novamente no painel.'));return fetch(api.url,{method:'POST',headers:{'Content-Type':'text/plain'},cache:'no-store',body:JSON.stringify(Object.assign({chave:api.chave,acao:'agendamentos',token:token},payload))}).then(function(r){if(!r.ok)throw Error('Falha de comunicação com a planilha.');return r.json();}).then(function(r){if(r.status==='sessao_expirada'){if(window.logoutPainelEmulti)window.logoutPainelEmulti();throw Error('Sessão expirada. Entre novamente.');}if(r.ok===false||r.status==='erro')throw Error(r.error||r.mensagem||'Operação não concluída.');return r;});}
function msgAg(text,error){var el=document.getElementById('agendamentosFeedback');if(el){el.textContent=text||'';el.className='agendamentos-feedback'+(error?' erro':'');}}
function dateAg(v){if(!v)return '';if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);var s=String(v).trim(),m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(/^\d{4}-\d\d-\d\d$/.test(s))return s;if(m)return m[3]+'-'+('0'+m[2]).slice(-2)+'-'+('0'+m[1]).slice(-2);var d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10);}
function escAg(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function renderAg(){var body=document.getElementById('agendamentosBody');if(!body)return;var q=(document.getElementById('agendamentosBusca').value||'').trim().toLocaleLowerCase('pt-BR'),pq=normAg(document.getElementById('agendamentosProfissional').value),pc=pq?profMapAg():null,semProf=!!pq&&!pc,list=semProf?[]:rowsAg.filter(function(r){if(q&&!String(r.Nome||'').toLocaleLowerCase('pt-BR').includes(q))return false;if(pq){var ps=pc.map[normAg(r.Nome)]||'';if(ps.indexOf(pq)<0)return false;}return true;});document.getElementById('agendamentosContagem').textContent=list.length+(list.length===1?' pessoa':' pessoas');if(!list.length){body.innerHTML='<tr><td colspan="8" class="agendamentos-vazio">'+(busyAg?'Carregando…':semProf?'Dados de profissionais indisponíveis. Atualize os dados do painel.':(q||pq)?'Nenhuma pessoa encontrada.':'Nenhum registro disponível. Sincronize Pessoas atendidas.')+'</td></tr>';return;}body.innerHTML=list.map(function(r){var ix=rowsAg.indexOf(r);return '<tr data-ag-ix="'+ix+'"><td class="agendamentos-nome">'+escAg(r.Nome)+'</td><td>'+escAg(r.Atendimentos)+'</td><td>'+escAg(r['Participantes Ativ. Coletiva'])+'</td><td>'+escAg(r.Total)+'</td><td><select data-ag="situacao" aria-label="Situação"><option'+((r.Situação||'Pendente')==='Pendente'?' selected':'')+'>Pendente</option><option'+(r.Situação==='Agendado'?' selected':'')+'>Agendado</option><option'+(r.Situação==='Realizado'?' selected':'')+'>Realizado</option><option'+(r.Situação==='Cancelado'?' selected':'')+'>Cancelado</option></select></td><td><input type="date" data-ag="dataAgendada" value="'+dateAg(r['Data agendada'])+'"></td><td><input type="text" maxlength="500" placeholder="Observações" data-ag="observacoes" value="'+escAg(r.Observações||'')+'"></td><td><button type="button" class="agendamentos-salvar" data-ag-save>Salvar</button></td></tr>';}).join('');}
function loadAg(){if(busyAg)return;busyAg=true;profCacheAg=null;msgAg('Carregando agendamentos…');renderAg();apiAg({action:'agendamentos.list'}).then(function(r){rowsAg=Array.isArray(r.rows)?r.rows:[];msgAg('');}).catch(function(e){msgAg(e.message||'Falha ao carregar.',true);}).finally(function(){busyAg=false;renderAg();});}
function syncAg(){if(busyAg)return;profCacheAg=null;var list=window.__emultiPessoasAtendidas&&window.__emultiPessoasAtendidas();if(!list||!Array.isArray(list.rows)||!list.rows.length){msgAg('Atualize os dados do painel para carregar Pessoas atendidas antes de sincronizar.',true);return;}var pessoas=list.rows.map(function(r){return{nome:String(r[0]||'').trim(),at:Number(r[1])||0,part:Number(r[2])||0,total:Number(r[3])||0};}).filter(function(x){return x.nome;});busyAg=true;msgAg('Sincronizando '+pessoas.length+' pessoas…');renderAg();apiAg({action:'agendamentos.sync',rows:pessoas}).then(function(r){msgAg('Sincronização concluída: '+(Number(r.inseridos)||0)+' novos; '+(Number(r.atualizados)||0)+' atualizados.');return apiAg({action:'agendamentos.list'});}).then(function(r){rowsAg=Array.isArray(r.rows)?r.rows:rowsAg;}).catch(function(e){msgAg(e.message||'Falha ao sincronizar.',true);}).finally(function(){busyAg=false;renderAg();});}
function saveAg(tr){var r=rowsAg[Number(tr.dataset.agIx)];if(!r)return;var btn=tr.querySelector('[data-ag-save]'),fields={};tr.querySelectorAll('[data-ag]').forEach(function(el){fields[el.dataset.ag]=el.value;});btn.disabled=true;btn.textContent='Salvando…';apiAg(Object.assign({action:'agendamentos.update',nome:r.Nome},fields)).then(function(){r.Situação=fields.situacao;r['Data agendada']=fields.dataAgendada;r.Observações=fields.observacoes;msgAg('Alterações de '+r.Nome+' salvas.');}).catch(function(e){msgAg(e.message||'Falha ao salvar.',true);}).finally(function(){renderAg();});}
document.addEventListener('DOMContentLoaded',function(){var b=document.getElementById('agendamentosBody');document.getElementById('agendamentosBusca').addEventListener('input',renderAg);var pf=document.getElementById('agendamentosProfissional');pf.addEventListener('input',renderAg);pf.addEventListener('focus',fillProfAg);document.getElementById('agendamentosAtualizar').addEventListener('click',loadAg);document.getElementById('agendamentosSincronizar').addEventListener('click',syncAg);document.querySelector('.tab[data-tab="agendamentos"]').addEventListener('click',loadAg);b.addEventListener('click',function(e){var btn=e.target.closest('[data-ag-save]');if(btn)saveAg(btn.closest('tr'));});b.addEventListener('change',function(e){if(e.target.dataset.ag==='situacao')saveAg(e.target.closest('tr'));});b.addEventListener('keydown',function(e){if(e.key==='Enter'&&e.target.matches('input[data-ag]')){e.preventDefault();saveAg(e.target.closest('tr'));}});});
